export { default as PageAccueil } from "./PageAccueil";
export { default as PageVols } from "./PageVols";
export { default as PageHotel } from "./PageHotel";
export { default as PageFavoris } from "./PageFavoris";
export { default as PageMentionsLegales } from "./PageMentionsLegales";
export { default as PageConfidentialites } from "./PageConfidentialites";
export { default as PageConditions } from "./PageConditions";
export { default as PageContact } from "./PageContact";
export { default as PageGestionCookies } from "./PageGestionCookies";
